### ISSUE TITLE
Missing convert_from function

### ISSUE THREAD

**Issue by toringe** [jasedit/pymmd#7]
Current version of pymmd has not implemented `convert_from` function as described under examples in README.

**Comment by jasedit** [comment]
For some reason, notifications were disabled for this repository, so I apologize for not spotting this sooner.

You can get approximately the same effect by using the `convert` function with the `dname` argument set to the directory to use for transclusion.

For the actual `convert_from` function, I can implement that shortly. Thanks for the bug report!
